feat: keep3r bonded relay
defi-wonderland/xkeeper-core pull request #1
Opened 2023-10-18 05:21 UTC by 0xJabberwock

2023-10-18 06:00 UTC, 0xJabberwock commented on solidity/interfaces/IKeep3rBondedRelay.sol
> +    address indexed _automationVault, address _bond, uint256 _minBond, uint256 _earned, uint256 _age
`Requirements` struct may be used here too.

2023-10-18 06:02 UTC, 0xJabberwock commented on solidity/test/integration/Keep3rBondedRelay.t.sol
> +    keep3rBondedRelay.setAutomationVaultRequirements(address(automationVault), address(kp3r), 1 ether, 0, 1 days);
How come these tests are passing? 😕

For reference, just in case: [Keep3rBondedJob.t.sol](https://github.com/defi-wonderland/keep3r-utils-private/blob/dev/solidity/test/e2e/Keep3rBondedJob.t.sol).

2023-10-20 11:40 UTC, ashitakah commented on package.json
> +    "build": "forge build --via-ir",
As we need to use more params in the happy path, foundry drop me an erro "Stack too deep", so 1 solution for this is compile with ir

2023-10-20 11:40 UTC, ashitakah commented on solidity/contracts/Keep3rBondedRelay.sol
> +    automationVaultRequirements;
👍

2023-10-20 11:42 UTC, ashitakah commented on solidity/contracts/Keep3rBondedRelay.sol
> +      IKeep3rBondedRelay.Requirements({bond: _bond, minBond: _minBond, earned: _earned, age: _age});
@0xJabberwock Should we check that bond is not address(0) or we understand that the owner should know this

2023-10-20 11:42 UTC, ashitakah commented on solidity/interfaces/IKeep3rBondedRelay.sol
> +  error Keep3rBondedRelay_NotAutomationVaultRequirement();
👍

2023-10-20 18:38 UTC, 0xJabberwock commented on solidity/contracts/Keep3rBondedRelay.sol
> +      IKeep3rBondedRelay.Requirements({bond: _bond, minBond: _minBond, earned: _earned, age: _age});
Upon introducing such a check in this function, there would be no way to unrequire an `automationVault`.

2023-11-15 18:11 UTC, 0xGorilla requested changes

2023-11-15 18:11 UTC, 0xGorilla commented on solidity/contracts/Keep3rBondedRelay.sol
> +    if (_execDataLength == 0) revert Keep3rRelay_NoExecData();
Shouldn't the errors here be prefixed with `Keep3rBondedRelay`?

2023-11-15 18:11 UTC, 0xGorilla commented on solidity/contracts/Keep3rBondedRelay.sol
> +        IKeep3rV2.isBondedKeeper.selector,
let's just call isKeeper here to set the initialGas, it will be less gas spending

2023-11-15 18:11 UTC, 0xGorilla commented on solidity/test/integration/Keep3rRelay.t.sol
> +  function test_issue_payment_keep3r(uint64 _fee, uint64 _howHard) public {
Is there any other important case you think we should test?

2023-11-15 18:11 UTC, 0xGorilla commented on solidity/utils/Constants.sol
> +address constant _KP3R_WHALE = 0x2FC52C61fB0C03489649311989CE2689D93dC1a2;
let's save the constants we can with the interface and not as plain `address`

2023-11-15 18:11 UTC, 0xGorilla commented on solidity/test/integration/Keep3rBondedRelay.t.sol
> +  }
isn't this shared between both Keep3rBondedRelay.t.sol and Keep3rRelay.t.sol. Let's please avoid code duplication wherever possible

2023-11-15 18:11 UTC, 0xGorilla commented on solidity/test/integration/Keep3rBondedRelay.t.sol
> +  }
I don't understand the goal of this test tbh. Looks like a unit test to me

2023-11-15 18:11 UTC, 0xGorilla commented on solidity/test/integration/Keep3rBondedRelay.t.sol
> +  }
I would actually merge both files into one: Keep3rRelays.t.sol, most of the logic is duplicated, even inside the test itself

2023-11-16 03:56 UTC, 0xJabberwock reviewed
Incredible refactorization! Code comments are lit. 🔥

2023-11-16 03:56 UTC, 0xJabberwock commented on solidity/interfaces/IKeep3rRelay.sol
> +  error Keep3rRelay_NotKeep3r();
Should be `NotKeeper`.

2023-11-16 03:56 UTC, 0xJabberwock commented on solidity/test/unit/AutomationVaultFactory.t.sol
> +  EnumerableSet.AddressSet internal _enumerableAutomationVaults;
`_enumerableAutomationVaults` is useless for the current test cases.

2023-11-16 03:56 UTC, 0xJabberwock commented on solidity/test/integration/Keep3rBondedRelay.t.sol
> +    bot = makeAddr('BOT');
`bot` is already set in `Common.t.sol`, so this line is duplicated and could be erased, as well as the analogous one in `Keep3rRelay.t.sol`.

2023-11-16 03:56 UTC, 0xJabberwock commented on solidity/test/integration/Keep3rBondedRelay.t.sol
> +  }
This test case expects event emissions within contracts other than the directly called one — following typical unit test conventions, such expectations wouldn't be possible.

2023-11-16 03:56 UTC, 0xJabberwock commented on solidity/test/integration/Keep3rBondedRelay.t.sol
> +  }
`_addJobAndLiquidity()` and `_bondAndActivateKeeper()` could be included in `Common.t.sol` in order to avoid duplication.

2023-11-16 03:56 UTC, 0xJabberwock commented on solidity/test/integration/Keep3rBondedRelay.t.sol
> +    // Execure the job
`Execure` should be `Execute`. Check `Keep3rRelay.t.sol` too.

2023-11-16 03:56 UTC, 0xJabberwock commented on solidity/contracts/Keep3rBondedRelay.sol
> +      revert Keep3rBondedRelay_NotAutomationVaultRequirement();
Observation: `minBond` is not checked.

2023-11-16 03:56 UTC, 0xJabberwock commented on solidity/contracts/Keep3rBondedRelay.sol
> +    if (_execDataLength == 0) revert Keep3rRelay_NoExecData();
`IKeep3rBondedRelay is IKeep3rRelay`, hence some errors are shared.

Should those interfaces be independent from each other? 🤔
Contracts are, since `Keep3rBondedRelay` does not inherit from `Keep3rRelay`.

2023-11-16 09:23 UTC, 0xGorilla commented on solidity/test/integration/Keep3rBondedRelay.t.sol
> +    // Execure the job
> _addJobAndLiquidity() and _bondAndActivateKeeper() could be included in Common.t.sol in order to avoid duplication.
Instead of that I would rather join both integration files into one

2023-11-16 09:24 UTC, 0xGorilla commented on solidity/contracts/Keep3rBondedRelay.sol
> +      revert Keep3rBondedRelay_NotAutomationVaultRequirement();
No need to check it, since it could be 0

2023-11-16 16:52 UTC, 0xJabberwock commented on solidity/contracts/Keep3rBondedRelay.sol
> +      revert Keep3rBondedRelay_NotAutomationVaultRequirement();
It could also be non-zero. 😶

2023-11-16 20:49 UTC, 0xJabberwock reviewed
✅ (Cannot formally approve since I opened the PR)

2023-11-16 20:49 UTC, 0xJabberwock commented on solidity/test/unit/Keep3rRelay.t.sol
> +    keep3rRelay.exec(_automationVault, _execDataKeep3r);
`_execDataKeep3r` should not be used within this test case — `exec()` should be called with just `_execData`, as it happens in others.

2023-11-20 11:22 UTC, ashitakah commented on solidity/test/integration/Keep3rBondedRelay.t.sol
> +  }
👍

2023-11-20 11:22 UTC, ashitakah commented on solidity/test/integration/Keep3rBondedRelay.t.sol
> +  }
👍

2023-11-21 11:37 UTC, 0xArdy commented on solidity/contracts/AutomationVaultFactory.sol
>      _automationVault = new AutomationVault(_owner, _organizationName);
shouldn't we remove the `_organizationName` param? @0xGorilla @ashitakah

2023-11-21 12:13 UTC, 0xGorilla commented on solidity/contracts/AutomationVaultFactory.sol
>      _automationVault = new AutomationVault(_owner, _organizationName);
yes

2023-11-21 13:01 UTC, 0xGorilla commented on solidity/contracts/AutomationVaultFactory.sol
> +  ) external view returns (address[] memory __automationVaults) {
```suggestion
    uint256 _amount
  ) external view returns (address[] memory _list) {
```

2023-11-21 13:04 UTC, 0xGorilla commented on solidity/contracts/Keep3rBondedRelay.sol
> +      revert Keep3rBondedRelay_NotAutomationVaultRequirement();
Yes, but the thing is that it is an optional parameter, so no need to check it here

2023-11-21 13:09 UTC, 0xGorilla commented on solidity/contracts/Keep3rRelay.sol
> +    // Ensure that the caller is a valid keeper
But it wasn't removed...

2023-11-21 13:11 UTC, 0xGorilla commented on solidity/test/integration/AutomationVault.t.sol
> +  }
only used once, no need for this function

2023-11-21 13:13 UTC, 0xGorilla commented on solidity/test/integration/AutomationVault.t.sol
> +    assertEq(IERC20(_DAI).balanceOf(newOwner), 0);
instead of checking that the balance is 0 (which is not a requirement), what do you think about storing the balance and then after the withdraw checking that the current balances equals the previous balance + 1000?

2023-11-21 13:14 UTC, 0xGorilla commented on solidity/test/integration/AutomationVault.t.sol
> +    // Check that the old owner cant withdraw funds
```suggestion
    // Check that the old owner can't withdraw funds
```

2023-11-21 13:15 UTC, 0xGorilla commented on solidity/test/integration/AutomationVault.t.sol
> +    automationVault.withdrawFunds(_ETH, 10, owner);
But you already checked this on the same test...

2023-11-21 13:17 UTC, 0xGorilla commented on solidity/utils/Constants.sol
> +address constant _DAI = 0x6B175474E89094C44Da98b954EedeAC495271d0F;
```suggestion
IERC20 constant _DAI = IERC20(0x6B175474E89094C44Da98b954EedeAC495271d0F);
```

2023-11-21 13:19 UTC, 0xGorilla commented on foundry.toml
> +gas_limit = 30_000_000
I'm talking about gas limit, try changing the one inside `[profile.test]` to 1. If the tests run it means the value is not being property used on tests

2023-11-21 13:20 UTC, 0xGorilla commented on solidity/test/integration/Keep3rBondedRelay.t.sol
> +  }
Let's please use the emoji reaction when it is a yes/no answer. What happened with this?

2023-11-21 20:23 UTC, ashitakah commented on solidity/utils/Constants.sol
> +address constant _DAI = 0x6B175474E89094C44Da98b954EedeAC495271d0F;
👍

2023-11-21 20:30 UTC, ashitakah commented on solidity/test/integration/AutomationVault.t.sol
> +    automationVault.withdrawFunds(_ETH, 10, owner);
I make sure that now the error is thrown with the new owner and not the old one, I could delete it but I think it's ok to leave it.

2023-11-21 20:31 UTC, ashitakah commented on solidity/test/integration/AutomationVault.t.sol
> +    // Check that the old owner cant withdraw funds
👍

2023-11-21 20:38 UTC, ashitakah commented on solidity/test/integration/AutomationVault.t.sol
> +    assertEq(IERC20(_DAI).balanceOf(newOwner), 0);
👍

2023-11-21 20:39 UTC, ashitakah commented on solidity/test/integration/AutomationVault.t.sol
> +  }
👍

2023-11-21 20:40 UTC, ashitakah commented on solidity/contracts/AutomationVaultFactory.sol
> +  ) external view returns (address[] memory __automationVaults) {
👍

2023-11-21 20:40 UTC, ashitakah commented on solidity/contracts/AutomationVaultFactory.sol
>      _automationVault = new AutomationVault(_owner, _organizationName);
👍

2023-11-22 10:01 UTC, 0xGorilla submitted a review, later dismissed

2023-11-22 10:02 UTC, ashitakah commented on solidity/contracts/Keep3rRelay.sol
> +    // Ensure that the caller is a valid keeper
Now done

2023-11-22 10:10 UTC, ashitakah commented on solidity/test/integration/Keep3rBondedRelay.t.sol
> +    emit Worked();
If it is already implemented, good catch!

2023-11-22 10:12 UTC, 0xGorilla commented on solidity/interfaces/IKeep3rBondedRelay.sol
> +    address indexed _automationVault, address _bond, uint256 _minBond, uint256 _earned, uint256 _age
This question was moved into a conversation with the data team in Discord. If the change is needed it is going to be handled on another PR

2023-11-22 10:30 UTC, 0xGorilla submitted a review, later dismissed

2023-11-22 10:57 UTC, 0xGorilla approved these changes

2023-11-22 10:58 UTC, ashitakah approved these changes

2023-11-22 10:59 UTC, merged