feat: keep3rsponsor.sol
defi-wonderland/xkeeper-core pull request #15
Opened 2024-03-08 17:41 UTC by 0xdeo

2024-03-13 12:53 UTC, ashitakah commented on solidity/contracts/core/Keep3rSponsor.sol
> +  IAutomationVault constant VAULT = IAutomationVault(0x255ed36E805aEf7f6ad94e3647fA0aED15dBb14D);
create as public immutable and define the value in the constructor. Also check the linter because constant starts with _

2024-03-13 12:53 UTC, ashitakah commented on solidity/contracts/core/Keep3rSponsor.sol
> +  IOpenRelay constant RELAY = IOpenRelay(0xE8E1b32340f527125721903a3947c937dc72e140);
same here

2024-03-13 12:54 UTC, ashitakah commented on solidity/contracts/core/Keep3rSponsor.sol
> +  modifier validateAndPayKeeper() {
close but not, you dont need a modifier you can implemented directly in the exec function

2024-03-13 12:56 UTC, ashitakah commented on solidity/contracts/core/Keep3rSponsor.sol
> +  IAutomationVault constant VAULT = IAutomationVault(0x255ed36E805aEf7f6ad94e3647fA0aED15dBb14D);
also, the vault should be passed as arguments in the exec, we will have several sponsored jobs and maybe the vault for each one is different

2024-03-13 12:56 UTC, ashitakah commented on solidity/contracts/core/Keep3rSponsor.sol
> +  modifier isSponsored(address job) {
is not used

2024-03-13 13:03 UTC, ashitakah commented on solidity/contracts/core/Keep3rSponsor.sol
> +    for (uint256 i = 0; i < jobs.length; i++) {
tip:

```
for (uint256 _i; _i < _jobs.length; ) {
    _sponsoredJobs.add(_jobs[_i]);

    unchecked{
        ++_i
    }
}
```

This is more gas efficient. ++i cheaper than ++i, unchecked avoid some issues and uint256 without 0 because is not needed

Also remember all underscores, you are missing in each method and variable. Remember that if is a storage without _ if is memory

2024-03-13 13:04 UTC, ashitakah commented on solidity/contracts/core/Keep3rSponsor.sol
> +  function removeJobs(address[] calldata jobs) public onlyOwner {
same here

2024-03-13 13:06 UTC, ashitakah commented on solidity/contracts/core/Keep3rSponsor.sol
> +    RELAY.exec(VAULT, _execData, msg.sender);
first exec and after that, emit the event

2024-03-13 13:06 UTC, ashitakah requested changes

2024-03-13 13:06 UTC, ashitakah commented on solidity/interfaces/core/IKeep3rSponsor.sol
> +pragma solidity 0.8.19;
Create a proper interface, you have several examples in xkeeper repo

2024-03-14 19:49 UTC, 0xdeo commented on solidity/contracts/core/Keep3rSponsor.sol
> +  modifier validateAndPayKeeper() {
Was the modifier incorrect in this case? Or should I just put this logic directly in the function

2024-03-14 20:04 UTC, 0xdeo commented on solidity/contracts/core/Keep3rSponsor.sol
> +  IAutomationVault constant VAULT = IAutomationVault(0x255ed36E805aEf7f6ad94e3647fA0aED15dBb14D);
Fixed.

2024-03-14 20:04 UTC, 0xdeo commented on solidity/contracts/core/Keep3rSponsor.sol
> +  IOpenRelay constant RELAY = IOpenRelay(0xE8E1b32340f527125721903a3947c937dc72e140);
Fixed.

2024-03-14 20:04 UTC, 0xdeo commented on solidity/contracts/core/Keep3rSponsor.sol
> +  modifier isSponsored(address job) {
Removed.

2024-03-14 20:04 UTC, 0xdeo commented on solidity/contracts/core/Keep3rSponsor.sol
> +    for (uint256 i = 0; i < jobs.length; i++) {
Fixed.

2024-03-14 20:04 UTC, 0xdeo commented on solidity/contracts/core/Keep3rSponsor.sol
> +  function removeJobs(address[] calldata jobs) public onlyOwner {
Fixed.

2024-03-14 20:04 UTC, 0xdeo commented on solidity/contracts/core/Keep3rSponsor.sol
> +  function jobSponsored(address job) public view returns (bool inSet) {
Fixed.

2024-03-14 20:04 UTC, 0xdeo commented on solidity/contracts/core/Keep3rSponsor.sol
> +    RELAY.exec(VAULT, _execData, msg.sender);
Fixed.

2024-03-14 20:04 UTC, 0xdeo commented on solidity/interfaces/core/IKeep3rSponsor.sol
> +pragma solidity 0.8.19;
Fixed.

2024-03-18 10:50 UTC, ashitakah commented on solidity/contracts/core/Keep3rSponsor.sol
> +  modifier validateAndPayKeeper() {
Yes it would be better if you put it in the function, think that you are using the modifier just 1 time, so is not needed to create a modifier.

2024-03-18 11:07 UTC, ashitakah requested changes

2024-03-18 11:07 UTC, ashitakah commented on solidity/contracts/core/Keep3rSponsor.sol
> +
also I would add a function to change the open relay, and move the open relay not as constant. I was thinking and maybe in the future we deploy a better open relay, so with the set, we dont need to deploy 2 contracts.

2024-03-18 11:07 UTC, ashitakah commented on solidity/contracts/core/Keep3rSponsor.sol
> +    // @note if _execData holds data for just 1 job, this is unnecessary
we never use @note inside the function we use just // and also left the   /// @inheritdoc IKeep3rSponsor

2024-03-18 11:07 UTC, ashitakah commented on solidity/interfaces/core/IKeep3rSponsor.sol
> +  error KeeperNotValid();
The errors have to start with the name of the contract Keep3rSponsor_KeeperNotValid()

2024-03-18 11:07 UTC, ashitakah commented on solidity/interfaces/core/IKeep3rSponsor.sol
> +  event JobExecuted(address _job);
event JobExecuted(address indexed _job);

2024-03-18 11:07 UTC, ashitakah commented on solidity/contracts/core/Keep3rSponsor.sol
> +  EnumerableSet.AddressSet private _sponsoredJobs;
the private variables need the natspec, something like : 
  /**
   * @notice Bleh
  */

2024-03-20 12:25 UTC, ashitakah requested changes
Looks good so far, remember the inheritdoc in what is inherited from the interface and that it is not necessary the ownable that we can make the logic by hand as much of the owner as of the propose the new one, you have an example in the automatioVault.

2024-03-20 12:25 UTC, ashitakah commented on solidity/contracts/core/Keep3rSponsor.sol
> +  /// @notice _sponsoredJobs Set of approved job addresses
No need 
```suggestion
  /// @notice Set of approved job addresses
```

2024-03-20 12:25 UTC, ashitakah commented on solidity/contracts/core/Keep3rSponsor.sol
> +contract Keep3rSponsor is Ownable, IKeep3rSponsor {
before contract something like:

/**
 * @title  AutomationVault
 * @notice This contract is used for managing the execution of jobs using several relays and paying them for their work
 */

2024-03-20 12:25 UTC, ashitakah commented on solidity/contracts/core/Keep3rSponsor.sol
> +  constructor(address _relay) Ownable() {
```suggestion
  constructor(IOpenRelay _relay) Ownable() {
```

2024-03-20 12:25 UTC, ashitakah commented on solidity/contracts/core/Keep3rSponsor.sol
> +  constructor(address _relay) Ownable() {
also if the constructor has param,   
   /**
   * @param _owner The address of the owner
   */

2024-03-20 12:25 UTC, ashitakah commented on solidity/contracts/core/Keep3rSponsor.sol
> +  function setRelay(address _relay) external onlyOwner {
```suggestion
  function setOpenRelay(IOpenRelay _relay) external onlyOwner {
```

2024-03-20 12:25 UTC, ashitakah commented on solidity/contracts/core/Keep3rSponsor.sol
> +  function exec(IAutomationVault.ExecData[] calldata _execData, IAutomationVault _vault) external {
```suggestion
  function exec(IAutomationVault.ExecData[] calldata _execData, IAutomationVault _automationVault) external {
```

2024-03-20 12:25 UTC, ashitakah commented on solidity/contracts/core/Keep3rSponsor.sol
> +  constructor(address relay) Ownable() {
check this again

2024-04-08 18:06 UTC, closed without merging