feat: doc
defi-wonderland/xkeeper-core pull request #2
Opened 2023-11-21 10:36 UTC by ashitakah

v1.0 doc

- Script for autogen doc
- Distribute the contracts in core and relays
- Clean external folder and get only the desired contracts
- All contracts have specific docu and 1 how to.

I would like to create more tutorials for the migration. Also I would like to have a css style.

Merge with the refactor is needed

2023-11-21 13:32 UTC, 0xGorilla commented on LICENSE
> +The MIT License (MIT)
Please use instead AGPL 3.0, copy it from here: https://github.com/defi-wonderland/sidechain-oracles/blob/dev/LICENSE

2023-11-21 13:32 UTC, 0xGorilla commented on README.md
> +[![License: MIT](https://img.shields.io/badge/License-MIT-blue.svg)](https://github.com/defi-wonderland/prophet-core/blob/main/LICENSE)
Also change it here. And you are linking to prophet, watch out

2023-11-21 13:35 UTC, 0xGorilla commented on solidity/contracts/core/AutomationVault.sol
>  // SPDX-License-Identifier: MIT
All of these changes in file structure should be in a separate PR

2023-11-21 13:42 UTC, 0xArdy requested changes
After this fix it should deploy a new preview

2023-11-21 13:42 UTC, 0xArdy commented on docs/src/SUMMARY.md
> +- [How to use]
```suggestion
- How to use
```

2023-11-21 17:16 UTC, 0xGorilla commented on README.md
> +[DeFi sucks](https://defi.sucks), but Wonderland is here to make it better.
```
## Contributors

Keep3r Framework was built with ❤️ by [Wonderland](https://defi.sucks).

Wonderland is the largest core development group in web3. Our commitment is to a financial future that's open, decentralized, and accessible to all. 

[DeFi sucks](https://defi.sucks), but Wonderland is here to make it better.
```

2023-11-21 22:43 UTC, ashitakah commented on LICENSE
> +The MIT License (MIT)
👍

2023-11-21 22:55 UTC, ashitakah commented on solidity/contracts/core/AutomationVault.sol
>  // SPDX-License-Identifier: MIT
👍

2023-11-21 23:02 UTC, ashitakah commented on README.md
> +[![License: MIT](https://img.shields.io/badge/License-MIT-blue.svg)](https://github.com/defi-wonderland/prophet-core/blob/main/LICENSE)
👍

2023-11-21 23:04 UTC, ashitakah commented on README.md
> +[DeFi sucks](https://defi.sucks), but Wonderland is here to make it better.
👍

2023-11-21 23:04 UTC, ashitakah commented on docs/src/SUMMARY.md
> +- [How to use]
👍

2023-11-22 21:44 UTC, 0xJabberwock requested changes
My copy editing report can be found below. 🧐

2023-11-22 21:44 UTC, 0xJabberwock commented on docs/src/content/howto/step_by_step.md
> +2. **Approval of selectors:**
The sub-section title is displayed after its corresponding content.

2023-11-22 21:44 UTC, 0xJabberwock commented on docs/src/content/intro/README.md
The content of this file makes multiple references to `Keep3r Framework`, including a link to the old repo. The license statement should be properly updated as well.

2023-11-22 21:44 UTC, 0xJabberwock commented on docs/src/content/relays/README.md
> +For more technical details about the interfaces of the core contracts, please refer to the `Interfaces` section in the technical documentation.
Interfaces of core contracts are mentioned here, but the content should be about relays' interfaces.

2023-11-22 21:44 UTC, 0xJabberwock commented on docs/src/content/relays/keep3r_relay.md
> +- **Keeper Authorization**: Validation mechanisms guarantee that only authorized Keepers within the Keep3r network can initiate and execute tasks, enhancing security and control.
In this case, `Keepers` word should be written uncapitalized, as it has been made other times.

2023-11-22 21:44 UTC, 0xJabberwock commented on docs/src/content/relays/open_relay.md
> +These gas metrics play a vital role in optimizing gas costs during task execution.
Do the gas metrics optimize gas costs? 🤨

2023-11-22 21:44 UTC, 0xJabberwock commented on docs/src/content/core/automation_vault_factory.md
> +- **Automation Vaults Listing**: Enables users to retrieve a list of deployed automation vaults, allowing for efficient tracking and monitoring.
This file displays twice `AutomationVaults`. I propose normalizing it to `automation vaults`, so it is more cohesive with the rest of the docs.

2023-11-27 15:53 UTC, ashitakah commented on README.md
> +# Prophet Core
HAHAH 👍

2023-11-27 15:54 UTC, ashitakah commented on README.md
> +XKeeper is a public good for on-chain automation. It should be very easy to create a job which can be run both by Keep3r, Gelato, Autonolas, or any other keeper out there. We have also deployed compa
👍

2023-11-27 15:54 UTC, ashitakah commented on README.md
> +cd keep3r-framework-core
👍

2023-11-27 15:55 UTC, ashitakah commented on README.md
> +Make sure to set `MAINNET_RPC` environment variable before running end-to-end tests.
👍

2023-11-27 15:57 UTC, ashitakah commented on README.md
> +[DeFi sucks](https://defi.sucks), but Wonderland is here to make it better.
👍

2023-11-27 16:01 UTC, ashitakah commented on docs/src/content/relays/README.md
> +For more technical details about the interfaces of the core contracts, please refer to the `Interfaces` section in the technical documentation.
👍

2023-11-27 16:02 UTC, ashitakah commented on docs/src/content/relays/keep3r_relay.md
> +- **Keeper Authorization**: Validation mechanisms guarantee that only authorized Keepers within the Keep3r network can initiate and execute tasks, enhancing security and control.
👍

2023-11-27 16:03 UTC, ashitakah commented on docs/src/content/relays/open_relay.md
> +These gas metrics play a vital role in optimizing gas costs during task execution.
you right

2023-11-27 16:05 UTC, ashitakah commented on docs/src/content/howto/step_by_step.md
> +2. **Approval of selectors:**
👍

2023-11-27 16:05 UTC, ashitakah commented on docs/src/content/core/automation_vault_factory.md
> +- **Automation Vaults Listing**: Enables users to retrieve a list of deployed automation vaults, allowing for efficient tracking and monitoring.
I like it, nice one

2024-02-22 10:55 UTC, merged